### ISSUE TITLE
希望可以添加一键部署到railway

### ISSUE THREAD

**Issue by DifferentSparkler** [Gladtbam/ms365_e5_renewx#1]
感觉在railway部署应用很方便希望开发者可以考虑下

warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
No XML encryptor configured. Key {ee0b2351-e3b7-4c3c-9dfd-e2f59706e995} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[0]
Now listening on: http://[::]:1066
info: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
Content root path: /renewx
这个是目前版本部署到railway的日志

**Comment by Gladtbam** [comment]
railway不是支持直接连接特定的GitHub仓库进行部署吗？
