### ISSUE TITLE
docker部署按照默认方式的，管理员密码还能第二次修改么？

### ISSUE THREAD

**Issue by aefa6** [Gladtbam/ms365_e5_renewx#6]
docker部署按照默认方式的，管理员密码还能第二次修改么？
服务程序版本：1.1.8171.24551 (2022-05-16 13:38:22 UTC+8)

**Comment by Gladtbam** [comment]
> docker部署按照默认方式的，管理员密码还能第二次修改么？ 服务程序版本：1.1.8171.24551 (2022-05-16 13:38:22 UTC+8)

可以，修改config.xml

**Comment by aefa6** [comment]
> > docker部署按照默认方式的，管理员密码还能第二次修改么？ 服务程序版本：1.1.8171.24551 (2022-05-16 13:38:22 UTC+8)
> 
> 可以，修改config.xml

我没找到config.xml的文件位置，这个是放在哪个文件夹的

**Comment by Gladtbam** [comment]
> 我没找到config.xml的文件位置，这个是放在哪个文件夹的

你既然能看到**默认部署**，那**自定义部署**应该不难看到吧？

**Comment by aefa6** [comment]
> > 我没找到config.xml的文件位置，这个是放在哪个文件夹的
> 
> 你既然能看到**默认部署**，那**自定义配置**应该不难看到吧？

看到了、但是不知道deploy文件夹的位置，我在root下pull镜像然后生成容器的，但是root文件夹下并没有生成额外的文件夹

**Comment by Gladtbam** [comment]
> 看到了、但是不知道deploy文件夹的位置，我在root下pull镜像然后生成容器的，但是root文件夹下并没有生成额外的文件夹

你选择默认部署，又不会把东西挂载出来，当然没东西在root文件夹下生成，你要在容器外修改就选择自定义，或者，你看看自定义自然就知道文件在/renewx/Delpoy/下

**Comment by aefa6** [comment]
> > 看到了、但是不知道deploy文件夹的位置，我在root下pull镜像然后生成容器的，但是root文件夹下并没有生成额外的文件夹
> 
> 你选择默认部署，又不会把东西挂载出来，当然没东西在root文件夹下生成，你要在容器外修改就选择自定义，或者，你看看自定义自然就知道文件在/renewx/Delpoy/下

所以我想请教下默认的如何修改密码..或者说其实是无法修改的？感谢耐心答复

**Comment by Gladtbam** [comment]
> 所以我想请教下默认的如何修改密码..或者说其实是无法修改的？感谢耐心答复

所以我不是告诉你路径了吗？而且如果不能修改，那个自定义部署弄出来干嘛？

**Comment by sofs2005** [comment]
默认命令配置文件都在docker里面需要进去改（不会的话去搜索一下吧），最好把配置拉出来部署，这样升级docker的话也没影响。

**Comment by aefa6** [comment]
> 默认命令配置文件都在docker里面需要进去改（不会的话去搜索一下吧），最好把配置拉出来部署，这样升级docker的话也没影响。

好的，感谢答复，我去百度下

**Comment by aefa6** [comment]
> > 所以我想请教下默认的如何修改密码..或者说其实是无法修改的？感谢耐心答复
> 
> 所以我不是告诉你路径了吗？而且如果不能修改，那个自定义部署弄出来干嘛？

好的，清楚了，我关闭issue
